
version: "3.4"

services:

# Nginx
  # nginx: 
  #   image: nginx:latest
  #   container_name: nginx
  #   restart: always
  #   volumes:
  #     - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ${HOST_VIDEO_DIR}:/app/videos 
  #   ports:
  #     - 8084:80

# Mqtt
  broker:
    image: toke/mosquitto
    restart: always
    expose:
      - "1883"
      - "9001"  
    volumes:
      - ./docker/mqtt/mosquitto_data:/mqtt/data
    network_mode: host
 
# Influxdb
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
  #  ports:
  #    - 8086:8086
    network_mode: host
    volumes:
      - ./docker/influxdb/data:/var/lib/influxdb


# Mongo
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: superAdmin
      MONGO_INITDB_DATABASE: dbS2
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodbdata:/data/db 
    networks:
      - backend


# StSupervisor
  stsupervisor:
    image: impleo/stsupervisor:1.0.16  
    container_name: stsupervisor
    restart: always  
  #  ports:
  #    - "${SUPERVISOR_PORT}:${SUPERVISOR_PORT}"
    network_mode: host
    depends_on:
      - broker
    volumes:
      - ./data/:/app/config/

# WebRtc SFU
  sfu:
    image: pionwebrtc/ion-sfu:latest-allrpc                                   
    restart: always
    environment:
      - gaddr=0.0.0.0:50051
      - jaddr=0.0.0.0:7000
    network_mode: host
    volumes:
      - "./docker/ion-sfu/config.toml:/configs/sfu.toml"

# WebRtc Streamer
  webrtc-streamer:   
    image: impleo/stserver-webrtc-streamer:1.0.2 
    container_name:  webrtc-streamer
    restart: always  
    network_mode: host
    depends_on:
      - broker
      - stsupervisor
      - sfu
    environment:
      VIDEO_BITRATE: "3500000"
      VIDEO_RESOLUTION: "1280x720"
    volumes:
      - ./data/:/app/data/


# StServer
  stserver:
    image: impleo/stserver:2.1.17
    container_name: stserver
    env_file: .env
    restart: always   
  #  ports:
  #    - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - broker
      - mongodb
    volumes:
      - ./data/:/app/data/
      - ./StServer.log:/app/StServer.log 
      - ${LICENSE_DIR}:/app/license/:rw   
      - ${HOST_VIDEO_DIR}:/app/videos/:rw 
      - ${HOST_ANNOTATIONS_DIR}:/app/annotations/:rw  
      - ${HOST_DOCUMENTS_DIR}:/app/documents/:rw 
      - ${HOST_UPLOAD}:/app/upload/:ro   
    network_mode: host
   

networks:
  backend:

volumes:
  mongodbdata:
    external: false