# This is a basic workflow to help you get started with Actions

name: CreateRelease

# Controls when the workflow will run
on:
  push:
    branches: [ master ]  
 #   tags:
 #   - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1

      # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

     # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.



