# This is a basic workflow to help you get started with Actions

name: CreateRelease

# Controls when the workflow will run
on:
  push:
    #branches: [ master ]  
    tags:
    - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
   
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          tar -czvf stserver-install.tar.gz ./install
          ls -la
   
    # - uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: "*.md,*.json"
    #     bodyFile: "README.md"
    #     token: ${{ secrets.TEST_TOKEN }}
     


